# Generated by Django 4.2 on 2023-04-20 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='shop.product')),
            ],
        ),
    ]
